/**
 * @file    configurePage.c
 * @author  shaggydogs & smartfox
 * @date    10/01/15
 * @brief   Manage the configuratio page creation. The configuration page is the page in wich the user selects for exemple if he want to activate the reaction module. It's the page that is displayed when the users open the application.
 **/

#include "configurePage.h"


extern gui_t *gui;

/**
 * @var     selectMissionDialog
 * @brief   informations that are sent to the rest of the program to indicate what have been selected via the gui.
 **/
GtkWidget *selectMissionDialog;

void close_mission_popup(GtkWidget *widget, gpointer data);

GtkWidget *comboMission;
GList *listMission = NULL;



#if GTK_CHECK_VERSION (2, 6, 0)
#define combo_box_active_get_text(combo_box) gtk_combo_box_get_active_text (combo_box)
#else
char *combo_box_active_get_text (GtkComboBox *combo_box)
{
	gchar *s_text = NULL;
	gboolean b_ret = FALSE;
	GtkTreeIter iter;

	g_return_val_if_fail (combo_box != NULL, s_text);

	b_ret = gtk_combo_box_get_active_iter (combo_box, &iter);
	if (b_ret)
	{
		GtkTreeModel *p_model = NULL;

		p_model = gtk_combo_box_get_model (combo_box);
		if (p_model != NULL)
		{
			gtk_tree_model_get (p_model, &iter, 0, &s_text, -1);
		}
	}
	return s_text;
}
#endif


/*
 * Fonction qui recupere les donnees de l'element courant affiche.
 */
combo_data_st get_active_data (GtkComboBox * p_combo)
{
	GtkTreeModel   *  p_model = NULL;
	GtkTreeIter iter;
	combo_data_st p_st;


	/* On recupere le modele qu'on a cree. */
	p_model = gtk_combo_box_get_model (p_combo);

	/* On recupere le GtkTreeIter de l'element courant. */
	if (gtk_combo_box_get_active_iter (p_combo, &iter))
	{
		/*
		 * On recupere les donnees de l'element courant a savoir
		 * un entier et une chaine de caracteres.
		 */
		gtk_tree_model_get (
		        p_model,
		        &iter,
		        0, &p_st.index,
		        1, &p_st.p_text,
		        -1
		        );
	}


	return p_st;
}


/**
 * @fn      chooseMission
 * @brief   displays a dialog that ask the user to select the mission he wants to use.
 */
void chooseMission(){
	GtkWidget *Bouton;
	gint i;
	GtkTreeIter iter;

    // Create a dialog window to ask the user to select the mission he wants
	selectMissionDialog = gtk_dialog_new();
	gtk_window_set_title(GTK_WINDOW(selectMissionDialog), "Select your mission");
	gtk_widget_show(selectMissionDialog);

	GtkListStore * p_model = gtk_list_store_new (2, G_TYPE_INT, G_TYPE_STRING);
	comboMission = gtk_combo_box_new_with_model (GTK_TREE_MODEL (p_model));

	GtkCellRenderer * p_cell = NULL;

	p_cell = gtk_cell_renderer_text_new ();
	gtk_cell_layout_pack_start (GTK_CELL_LAYOUT (comboMission), p_cell, FALSE);
	gtk_cell_layout_set_attributes (
	        GTK_CELL_LAYOUT (comboMission),
	        p_cell, "text", 0,
	        NULL
	        );

	p_cell = gtk_cell_renderer_text_new ();
	gtk_cell_layout_pack_start (GTK_CELL_LAYOUT (comboMission), p_cell, FALSE);
	gtk_cell_layout_set_attributes (
	        GTK_CELL_LAYOUT (comboMission),
	        p_cell, "text", 1,
	        NULL
	        );

	for(i=0; i<6; i++)
    {
		/* Create the description of each missions. */
		gtk_list_store_append (p_model, &iter);
		gtk_list_store_set (
		        p_model, &iter,
		        0, i, 1,mission_select_list[i],
		        -1
		        );
	}
	gtk_box_pack_start(GTK_BOX(GTK_DIALOG(selectMissionDialog)->vbox), comboMission, TRUE, TRUE, 0);
	gtk_widget_show(comboMission);

    // Creation of the select button used to valid the choice.
	Bouton = gtk_button_new_with_label("Select");
	gtk_signal_connect_object(GTK_OBJECT(Bouton), "clicked", (GtkSignalFunc)check_selected_mission_id, NULL);
	gtk_box_pack_start(GTK_BOX(GTK_DIALOG(selectMissionDialog)->action_area), Bouton, TRUE, TRUE, 0);

    // Connection of the close signal
	gtk_signal_connect_object(GTK_OBJECT(selectMissionDialog), "closed", (GtkSignalFunc)close_mission_popup, NULL);

	gtk_widget_show(Bouton);

}


/**
 * @brief       Function called when the user clicks on the close button of the dialog.
 * @param       widget      the widget that generated the call of this function.
 * @param       data        the date generated by the click event
 **/
void close_mission_popup(GtkWidget *widget, gpointer data){
	printf("Error: Please select a mission.");
}


void configPage(){
	/*-----create chars to put texts for infobulles-----*/
	char infoBullSaturation[2000] = "It limits commands which could be sent to the drone in order to ensure that the safety procedures could be done efficiently";
	char infoBullSePoser[2000] = "The drone will land if an error is detected (if not activated, first try an automatic emergency procedure)";
	char infoBullSMLimited[2000] = "Emergency procedures are not activated for minor faults (ie: top obstacle and bottom obstacle)";
	char infoBullDebug[2000] = "Enable the user to see all informations dynamically on diagnosis and safety softwares (in the debug window) and create log files that register all information during execution";
	char infoBullSys[2000] = "It will send a landing order if drone state is too dangerous,and any procedure could protect the drone. It may not work for high speeds.";
	char infoBullMission[2000] = "It will start a mission for filling the database which it is used for the learning process";
	char infoBullReaction[2000] = "It will activate the openMinded Safety Mode";

	/*-----Create a table of 8 rows and 7 lines-----*/
	gui->tableConfigPage = gtk_table_new(7, 8, TRUE);
	gtk_table_set_col_spacings(GTK_TABLE(gui->tableConfigPage), 10);

	/*-----create the labels-----*/
	gui->labelConfigPageTop = gtk_label_new (NULL);
	gtk_label_set_markup (GTK_LABEL (gui->labelConfigPageTop),
	                      "<b>Configure the following parameters to start the application</b>");
	gui->labelSF = gtk_label_new ("Open Source Project");

	/*-----create check buttons ------*/
	gui->checkButtonSaturation = gtk_check_button_new_with_label("Saturation");
	gui->checkButtonSys = gtk_check_button_new_with_label("Extreme Emergency System ");
	gui->checkButtonSePoser = gtk_check_button_new_with_label("Landing");
	gui->checkButtonSMLimited = gtk_check_button_new_with_label("Limited Smart Safety Mode");
	gui->checkButtonDebug = gtk_check_button_new_with_label("Debug mode");
	gui->checkButtonMission = gtk_check_button_new_with_label("Mission for learning process");
	gui->checkButtonReaction = gtk_check_button_new_with_label("Enable openMinded Safety Mode");

	/*-----create finish button-----*/
	gui->buttonFinish = gtk_button_new_with_label("Finish");
	gtk_widget_set_size_request(gui->buttonFinish, 90, 40);
	/*-----add connect to finish button-----*/
	gtk_signal_connect (GTK_OBJECT(gui->buttonFinish), "clicked",
	                    GTK_SIGNAL_FUNC (check_button_callback), NULL);

	/*-----create tooltips-----*/
	gui->tooltipsSaturation = gtk_tooltips_new ();
	gui->tooltipsSePoser = gtk_tooltips_new ();
	gui->tooltipsSMLimited = gtk_tooltips_new ();
	gui->tooltipsDebug = gtk_tooltips_new ();
	gui->tooltipsSys = gtk_tooltips_new ();
	gui->tooltipsMission = gtk_tooltips_new ();

	/*-----associate tooltips with its checkbutton-----*/
	gtk_tooltips_set_tip (gui->tooltipsSePoser,gui->checkButtonSePoser,infoBullSePoser, NULL);
	gtk_tooltips_set_tip (gui->tooltipsSMLimited, gui->checkButtonSMLimited,infoBullSMLimited, NULL);
	gtk_tooltips_set_tip (gui->tooltipsDebug, gui->checkButtonDebug,infoBullDebug, NULL);
	gtk_tooltips_set_tip (gui->tooltipsSys, gui->checkButtonSys,infoBullSys, NULL);
	gtk_tooltips_set_tip (gui->tooltipsSaturation, gui->checkButtonSaturation,infoBullSaturation, NULL);
	gtk_tooltips_set_tip (gui->tooltipsSaturation, gui->checkButtonSaturation,infoBullSaturation, NULL);
	gtk_tooltips_set_tip (gui->tooltipsMission, gui->checkButtonMission,infoBullMission, NULL);
	gtk_tooltips_set_tip (gui->tooltipsReaction, gui->checkButtonReaction, infoBullReaction, NULL);

	/*-----create smart fox image-----*/
	gui->pixbuf = gdk_pixbuf_new_from_file_at_size("logo_OM.png",40,40,NULL);
	gui->imgSmartFox = gtk_image_new_from_pixbuf(gui->pixbuf);

	/*-----create vbox which contains all checkboxes -----*/
	gui->vboxCheckButton = gtk_vbox_new(TRUE, 20);

	/*-----creat aligns-----*/
	gui->valignCheckButton = gtk_alignment_new(0, 0, 0, 0);
	gui->halignButtonFinish = gtk_alignment_new(0, 0, 0, 0);

	/*-----add checkboxes to the vbox and set the size of 300*220-----*/
	gtk_container_add(GTK_CONTAINER(gui->vboxCheckButton), gui->checkButtonSaturation);
	gtk_widget_set_size_request(gui->vboxCheckButton,300,220);
	gtk_container_add(GTK_CONTAINER(gui->vboxCheckButton), gui->checkButtonSys);
	gtk_container_add(GTK_CONTAINER(gui->vboxCheckButton), gui->checkButtonSePoser);
	//gtk_container_add(GTK_CONTAINER(gui->vboxCheckButton), gui->checkButtonSMLimited);
	gtk_container_add(GTK_CONTAINER(gui->vboxCheckButton), gui->checkButtonDebug);
	gtk_container_add(GTK_CONTAINER(gui->vboxCheckButton), gui->checkButtonMission);
	gtk_container_add(GTK_CONTAINER(gui->vboxCheckButton), gui->checkButtonReaction);

	/*-----add finish button to haligh-----*/
	gtk_container_add(GTK_CONTAINER(gui->halignButtonFinish), gui->buttonFinish);

	/*-----add vbox to valign-----*/
	gtk_container_add(GTK_CONTAINER(gui->valignCheckButton), gui->vboxCheckButton);

	/*-----add components to the table-----*/
	gtk_table_attach_defaults(GTK_TABLE(gui->tableConfigPage), gui->labelConfigPageTop, 0,8,0,1);
	gtk_table_attach_defaults(GTK_TABLE(gui->tableConfigPage), gui->valignCheckButton, 1,8,1,5);
	gtk_table_attach_defaults(GTK_TABLE(gui->tableConfigPage), gui->halignButtonFinish, 6,8,4,6);
	gtk_table_attach_defaults(GTK_TABLE(gui->tableConfigPage), gui->imgSmartFox, 2,3,5,6);
	gtk_table_attach_defaults(GTK_TABLE(gui->tableConfigPage), gui->labelSF, 1,8,5,6);

	/*-----add table to frame associated to this configure page-----*/
	gtk_container_add (GTK_CONTAINER (gui->frameNoteBook), gui->tableConfigPage);
}



void hideMissionSelectionDialog(){
    gtk_widget_hide(selectMissionDialog);
}


combo_data_st getSelectedMissionFromCombo(){
    return get_active_data((GtkComboBox *)comboMission);
}
