#!/bin/bash
SCRIPT=".plotlog.gnuplot"

# Plot the log file of trainmsvm with gnuplot
# and save plot to a .ps file

GNUPLOT=`command -v gnuplot -e quit`
if [ "$GNUPLOT" = "" ]
then
	echo "Gnuplot not found. Cannot plot log file."
	exit
fi

if [ $# -lt 1 ];
then 
	echo "Usage: plotlog logfile.log [plotfile.ps]"
	exit
fi

LOGFILE=$1

if [ -f $LOGFILE ];
then
	echo "Plotting log file $LOGFILE..."
else
	echo "Log file $LOGFILE not found."
	exit
fi

if [ $# -gt 1 ] ;
then
	PSFILE=$2
else
	PSFILE=$LOGFILE.ps
fi

echo "set term postscript enhanced color" > $SCRIPT
echo "set output \"$PSFILE\" ; set size .8,.8" >> $SCRIPT
echo "plot \"$LOGFILE\" using 1:2 lt 1 title \"value of the dual objective\" with linespoints, \"$LOGFILE\" using 1:3 lt 2 title \"upper bound on the optimum\" with linespoints" >> $SCRIPT
echo "set term wxt ; set output ; set size 1.,1. ; replot" >> $SCRIPT

gnuplot -persist $SCRIPT

echo "Plot saved as $PSFILE"
